### ISSUE TITLE
是否可以使用真实数据？

### ISSUE THREAD

**Issue by chopchopjames** [MingyuJ666/Stockagent#1]
这个项目真是太棒了，我在考虑把项目中的模拟数据变成真实数据，放在现实中做检验，计划做以下几个改动：

1. 选择业务稳定的股票池，使用Damodaran的DCE估值法来进行估值，在估值折价区间增加一个“企业”agent，用一定比例的现金流模拟企业回购的行为。（增加一个buyback_plan方法？）
2. 增加character的类型，比如value（折价区间买入，增加持仓周期），trend（只在上涨时买入，下跌时卖出）。
3. 增加env（大盘？），来调整character，env用GDP的增长+std来模拟指数收益率，在指数价格低位时character变得更加保守，高位时变得更加积极。

请问这样的改动是否合理？

**Comment by franz-chang** [comment]
这些改动基本是合理的。

1.我们使用的FCFF估值法是受限于模拟中很受限上市公司数量不得已选择的估值方法，如果有一个板块的上市公司股票池数据是可以使用DCE估值法的。
2. 关于增加character类型是可以的，完全可以将任务往量化工程角度去设计，我们Stockagent得益于Xinyi Liu出色的代码是可以稳定运行的。不过增加指标和参数要注意API的计算量。

**Comment by chopchopjames** [comment]
非常感谢您的回复，我先按照这个思路试试哈

**Comment by MingyuJ666** [comment]
Thank you for acknowledging our efforts. We hope you can provide more valuable insights and be eager to reference my work in the future. Thank you!
