### ISSUE TITLE
packages in requirements have conflicting dependencies.

### ISSUE THREAD

**Issue by RayleighZ** [MingyuJ666/Stockagent#2]
In requirements.txt, there are two dependencies for pandas with different versions (1.3.5 and 1.3.4), which cause the error ERROR: Cannot install pandas==1.3.4 and pandas==1.3.5 because these package versions have conflicting dependencies. Should I remove one of them?
![image](https://github.com/user-attachments/assets/6a1fc924-504e-4c19-8cea-2c528667e391)
![a92fc17e1ae70031f8ba497e70a443f7](https://github.com/user-attachments/assets/a8284534-a832-42c5-8708-35d956922d7c)

**Comment by MingyuJ666** [comment]
I think the pandas version did not really impact the final result; you can just remove one of them. I will update the code soon.
